# Generated by Django 2.2.19 on 2022-12-24 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('title', models.CharField(max_length=100)),
                ('artist', models.CharField(max_length=40)),
                ('genre', models.CharField(choices=[('R', 'Рок'), ('E', 'Электроника'), ('P', 'Поп'), ('C', 'Классика'), ('O', 'Саундтреки')], default='R', max_length=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('comment', models.CharField(max_length=1024)),
            ],
        ),
    ]
